cursos = ["Engenharia da computacao", "Engenharia civil", "Engenharia eletrica", "Engenharia de controle e automacao", "Engenharia eletronica",
            "Engenharia de telecomunicacoes"]


disciplinas = ["CENARIOS DE TECNOLOGIA DA INFORMACAO", "FUNDAMENTOS DE REDES DE COMPUTADORES", "INTRODUCAO A PROGRAMACAO", "LINGUA PORTUGUESA",
                "ORGANIZACAO E ARQUITETURA DE COMPUTADORES", "GESTAO DE SERVICOS PARA TI", "INOVACAO TECNOLOGICA E EMPREENDEDORISMO", "MATEMATICA COMPUTACIONAL",
                "NEGOCIOS ELETRONICOS", "SEGURANCA DA INFORMACAO", "TECNOLOGIA PARA INTERNET I", "ESTRUTURA DE DADOS", "PARADIGMAS DE LINGUAGENS DE PROGRAMACAO",
                "PROBABILIDADE E ESTATISTICA COMPUTACIONAL", "PROGRAMACAO I", "PROJETO DE BANCO DE DADOS", "ALGORITMOS AVANCADOS", "ANALISE DE FUNCOES",
                "IMPLEMENTACAO DE BANCO DE DADOS", "PROGRAMACAO DE SOFTWARE BASICO", "SISTEMAS OPERACIONAIS", "CALCULO PARA CIENCIA DA COMPUTACAO",
                "GEO. ANALITICA E ALGEBRA LINEAR PARA COMPUTACAO", "LINGUAGEM DE MONTAGEM", "SISTEMAS DIGITAIS", "TEORIA DOS GRAFOS", "ANALISE NUMERICA", "COMPILADORES", 
                "ENGENHARIA DE USABILIDADE E INTERFACES", "LINGUAGENS FORMAIS E AUTOMATOS", "MODELAGEM DE SISTEMAS", "PROGRAMACAO DE MICROCONTROLADORES",
                "SISTEMAS DISTRIBUIDOS", "FUNDAMENTOS DE ENGENHARIA DE SOFTWARE", "GERENCIA DE PROJETOS DE TI", "INTELIGENCIA COMPUTACIONAL E ARTIFICIAL",
                "INTERNET DAS COISAS", "PROGRAMACAO II", "COMPUTACAO EM NUVEM", "COMPUTACAO GRAFICA E PROCESSAMENTO DE IMAGEM",
                "PROJETO DE CIENCIA DA COMPUTACAO", "SEGURANCA DE SISTEMAS COMPUTACIONAIS", "SISTEMAS EMBARCADOS"]             